### PR TITLE
Made Cart Button functional added billing.html 

### PR DESCRIPTION
**Pull request by killerraj369**
Hey,
I have made cart button functional. Now when users clicks on the button it takes you to the billing page. 
Kindly Merge the PR

### CODE REVIEW

**Comment by ahmadsohail404** [comment]
please attach a screenshot

**Comment by killerraj369** [comment]
yes here it is

Screenshot_1
This billing page is good enough. Kindly Merge the PR

**Comment by killerraj369** [comment]
I have also made pointer cursor on Add Cart Button

**Comment by killerraj369** [comment]
Hy @ahmadsohail404 ,
Have you reviewed the changes. ? If you want me to improve then let me know

**Pull request merged**
